### ISSUE TITLE
Show an alert when there are pending transactions

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#123]
Each time the balance is updated, the list of pending transactions must be verified. If there are any pending transactions affecting any of the user addresses, an alert should be shown to the user, just as happens in the desktop wallet right after making a transaction.

Additionally, while the alert is displayed the balance update period should be reduced from 5 minutes to 20 seconds.

**Comment by alexandermushinskiy** [comment]
@Senyoret1, there is api call `this.apiService.get('wallet/transactions', { id: wallet.filename })` which is used to get pending transactions in the desktop wallet. In the web wallet there is no wallet id (wallet.filename). Should we use another api or we are move in the wrong direction?

**Comment by alexandermushinskiy** [comment]
@Senyoret1, thanks for the quick response. Also please be informed that the issue is implemented and appropriate PR is created.
