### ISSUE TITLE
The header shows invalid data when opening the wallet.

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#127]
Just after opening the wallet, the following is shown for a brief moment:
![100](https://user-images.githubusercontent.com/34079003/40152235-6e67dffa-5952-11e8-8286-570518e07049.png)
As soon as it is detected that the node has 100% synchronization, it should exit the state in which the synchronization percentage and the current block are shown.

**Comment by alexandermushinskiy** [comment]
Please be informed that the issue has been fixed and PR has been created.
