### ISSUE TITLE
It is necessary to add a margin at the bottom of most pages

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#128]
The content of all the pages have some margin at the top, like this:
![margin](https://user-images.githubusercontent.com/34079003/40152622-00a15bac-5954-11e8-952d-6d77f634c1b6.png)
However, the content of no page, with the exception of the wallets page, have a lower margin. All pages should have a lower margin of the same size as the top margin.

**Comment by alexandermushinskiy** [comment]
@Senyoret1, it's not clear what should be done in scope of this issue. Could you please take a look at pic (it  is attached) and help us to understand? We marked there two possible places 
![image](https://user-images.githubusercontent.com/30319973/40186314-76ff12b8-59fd-11e8-88d3-b239d6438148.png)

**Comment by Senyoret1** [comment]
Basically, all screens have this problem:
![margins](https://user-images.githubusercontent.com/34079003/40191005-3f2b301c-59ce-11e8-9a41-fb93706fab2e.png)

The margin at the bottom should be 30 pixels too.

An important detail is that the message at the top that warns users that they could lose coins modifies the scroll behavior, so it is necessary to remove it temporarily while working in this issue, to be able to notice the problem as in the image.

On the other hand, the wallets page does have a lower margin, but it is too large. On that screen you should simply remove the additional 74 pixels added by the action buttons container.

**Comment by alexandermushinskiy** [comment]
@Senyoret1, thank you for your additional explanation, it's clear now. The appropriate PR with a fix has been created.
