### ISSUE TITLE
Problem when calculating how many hours to return

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#135]
When creating a transaction, this line can return a number with decimals, which is not allowed:
https://github.com/skycoin/skycoin-web/blob/e29d2ee5f8f154146f0c6521cbf668e3e82204e4/src/app/services/wallet.service.ts#L90
It should use `parseInt`.

Additionally, there is an error in `unburnedHouarsRatio`, it should be named `unburnedHoursRatio`, without the "a".

**Comment by alexandermushinskiy** [comment]
The bug has been fixed, the PR is ready for review.
