### ISSUE TITLE
The updating process may fail

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#145]
Here the balance updating procedure is restarted:
https://github.com/skycoin/skycoin-web/blob/95f7bac855b5d2b5377214d6e21cd3074e29b0cd/src/app/services/wallet.service.ts#L324-L326
The `if` should check `>=` instead of `===`, since there are several cases in which the clock might not run in the exact amount of time.

**Comment by alexandermushinskiy** [comment]
The issue has been fixed, a PR has been created.
