### ISSUE TITLE
Update the style of the wallets page

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#157]
The necessary changes are:

- Show/hide the addresses if the user presses anywhere in the wallet row (such as in the desktop wallet), not only if he clicks on the arrow at the right.

![areas](https://user-images.githubusercontent.com/34079003/40498671-a28bc21e-5f4d-11e8-8ae1-2a83ad06b48e.png)

- Replace the unspent outputs and copy address buttons with the drop-down menu used in the desktop wallet.

- Align coins/hours to the right.

- Removed `cursor:pointer` from address row.

Please use https://github.com/skycoin/skycoin/pull/1411 as reference.

**Comment by alexandermushinskiy** [comment]
@Senyoret1, we have two questions:
1) should we add "Unlock wallet" button near the "Edit wallet" button, the similar as we have "Encrypt wallet" in the desktop wallet (see attached pic)?
2) should we remove ability to unlock wallet functionality by clicking lock icon as it is implemented in the desktop wallet (it just uses for showing a state)?

![image](https://user-images.githubusercontent.com/30319973/40548595-ce6048b0-603d-11e8-98fa-9932f0fcbb02.png)

**Comment by Senyoret1** [comment]
For now neither of the two changes is necessary. It is very likely that changes will be made to the unlock wallet button, but I am still not completely sure about what is the best option, so it is better not to touch it for now.

**Comment by alexandermushinskiy** [comment]
The issue has been implemented and PR is ready.
