### ISSUE TITLE
Style improvements

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#158]
The outputs screen needs more space between it elements. Please use the following margins:
![margins](https://user-images.githubusercontent.com/34079003/40499916-5218a56e-5f51-11e8-8ec4-e00a168cbb97.png)

Also, please remove the `-wallet` class in the following lines:
https://github.com/skycoin/skycoin-web/blob/6eedb6576b5572e1aa0d2e6fc6af2270682d19cb/src/app/components/pages/settings/outputs/outputs.component.html#L4
https://github.com/skycoin/skycoin-web/blob/6eedb6576b5572e1aa0d2e6fc6af2270682d19cb/src/app/components/pages/settings/outputs/outputs.component.html#L6

**Comment by alexandermushinskiy** [comment]
The issue has been implemented, PR has been created.
