### ISSUE TITLE
Names format

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#159]
Please give each commit a different name, describing what it does, like in https://github.com/skycoin/skycoin/commits/develop. There is no problem with adding the issue number at the beginning, but ideally it should include only the number, without "issue" at the beginning. This is because some prs have many commits and currently all have the same name, which makes it difficult to see the history on Github.

**Comment by alexandermushinskiy** [comment]
Ok, we will follow this rule in future commits:
#[issue_number]: [what was implemented/fixed].
Don't you mind if the initial commit will include the name of an issue (e.g. for the current issue it will look like: "#159: Names format")?

**Comment by Senyoret1** [comment]
I think it's fine if the initial commit includes the name of the issue, as have been done until now. The problem is just with having many commits with the same name.
