### ISSUE TITLE
Optimizations for balance updating

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#166]
Add a flag in `WalletService` to know if `loadBalances()` is currently obtaining data from the server. If `loadBalances()` is obtaining data, do not update the balance in the last "if" of
https://github.com/skycoin/skycoin-web/blob/e84fe468c75e33ace92d8bbb39cb49d7880b35aa/src/app/services/wallet.service.ts#L395-L406

**Comment by alexandermushinskiy** [comment]
@Senyoret1, should we replace the condition the last "if" by the flag?
It's not clear when this flag should be reset, in another words what is a condition when a balance should be updated?

**Comment by Senyoret1** [comment]
The problem that should be solved goes like this:

The user sends a transaction, `loadBalances()` is called to update the balance and an alert is shown indicating that there are pending transactions. As there are pending transactions, after 20 seconds `calculateTimeSinceLastUpdate()` is called, which in turn calls `loadBalances()` for updating the balance. However, the server is saturated, so after 20 seconds the balance has not yet been obtained, `calculateTimeSinceLastUpdate()` and `loadBalances()` are called again and the user is now requesting the balance 2 times (saturating the server even more). With a flag indicating that the connection initiated by the first call to  `loadBalances()` is still active, the second call, which is unnecessary, could be avoided.

The flag could be set to true at the start of `loadBalances()` and to false in the complete event of the connection (`loadBalances()`has several observables, so it would be good to be careful), for example. In the initial comment I thought about puting in the if condition of `calculateTimeSinceLastUpdate()` something like this: `if (timeSinceLastUpdate >= this.refreshBalancesTimeInSec && !updatingBalance)`. However, it would be much better to simply put something like that at the start of `loadBalances()`: `if (updatingBalance) return;` An option that could be even better would be not to use a flag, but the observable of the last connection, and check if it has already finished, that way it will not be necessary to manually set the flag to `false` and it would be less likely to make mistakes.

**Comment by alexandermushinskiy** [comment]
The issue is implemented.
