### ISSUE TITLE
Some unnecessary tooltips are being shown

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#167]
If you leave the mouse pointer over the header, a tooltip like this appears:
![tooltip](https://user-images.githubusercontent.com/34079003/40565464-b586265a-603a-11e8-9a26-3a4295fb834e.png)
That tooltip is unnecessary and negatively affects the UI.

The problem is that `HeaderComponent` has an input called `title`. When that property is assigned, the component reads it and places the title, but the browser does read it too, because `title` is an html property, and shows the tooltip. Because of this, the property must be renamed.

Additionally, all modal screens also have a `title` property, so it is necessary to rename that property in `ModalComponent` and replace it in all the places where it is being used.

**Comment by alexandermushinskiy** [comment]
@Senyoret1, to avoid unnecessary tooltips we can leave the name 'title' and use property binding which will fixed this problem.
instead of `<app-modal title="Edit Wallet"..>`
we will use `<app-modal [title]="'Edit Wallet'"`

**Comment by alexandermushinskiy** [comment]
The issue is fixed and ready for a review.
