### ISSUE TITLE
The lateral margins are not consistent

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#176]
The wallet pages consist, basically, of a header, a gray background and a white area, in which the main content is placed. That white area should have a margin of 30px on the left and on the right. However, this margin is respected only in the wallet page, in the outputs page and in the pending transactions page. The magis has to be added also in the blockchain page, in the history page and in the send coins page.

**Comment by alexandermushinskiy** [comment]
It is fixed and ready for review.
