### ISSUE TITLE
Add an option to delete wallets

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#177]

**Comment by alexandermushinskiy** [comment]
@Senyoret1, do you mean ability to delete all existing wallets by clicking an appropriate button "Delete Wallets" or ability to delete each wallet separately (see attached pic with both cases)?
Also Could you please approve that a confirmation message should be shown before actual deleting?

![image](https://user-images.githubusercontent.com/30319973/40630904-9ee4297c-62df-11e8-90a6-83f2bb7393db.png)

**Comment by Senyoret1** [comment]
I mean the ability to delete each wallet separately. However, adding the button at the top does not seem to be appropriate, because it is very close to the arrow. It would be better to add it next to the other option buttons, I think next to the one for editing the wallet:

![edt](https://user-images.githubusercontent.com/34079003/40635564-96b3c1ca-62c8-11e8-9d7e-5e4e776832e8.png)

You could use the same icon of the the hide empty button.

**Comment by alexandermushinskiy** [comment]
It's implemented and ready for review.
