### ISSUE TITLE
Encode the transaction before displaying the preview

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#188]
Currently, when sending a transaction, the transaction is oncoded and sent to the server when the user presses the "Send" button on the preview page. However, the transaction should be encoded (but not sended) right after the user presses the "Verify" button in the send coins form, just before displaying the preview page, in order to capture any error returned by `CipherProvider` and let the user correct it directly in the form.

**Comment by alexandermushinskiy** [comment]
The issue is implemented.
