### ISSUE TITLE
Add the arrow to the select in the send coins form

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#230]
This is the arrow shown in the desktop wallet:
![arrow](https://user-images.githubusercontent.com/34079003/40843728-f1cf0e66-657f-11e8-9530-58e7a7806d3d.png)
Additionally, to hide in all browsers the default arrow, it is necessary to change `-webkit-appearance: none;` in the css of the select by `appearance: none;`.

**Comment by alexandermushinskiy** [comment]
The issue is implemented.
