### ISSUE TITLE
Improvements for the preview of transactions

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#231]
The balance should be centered vertically, in relation to the transaction data:

![tx2](https://user-images.githubusercontent.com/34079003/40844437-e9d70a18-6581-11e8-85b9-dbac2d26e84f.png)
![tx1](https://user-images.githubusercontent.com/34079003/40844576-56a52f1c-6582-11e8-816c-806fe181346f.png)
Additionally, when seeing the details of a transaction from the history, the "coins" row is redundant, so it should be deleted.

**Comment by alexandermushinskiy** [comment]
The issue is implemented.
