### ISSUE TITLE
Close the MatSnackBar when navigatin from the send coins form

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#236]
After mergin https://github.com/skycoin/skycoin-web/pull/203 if a wrong address is used in the send form, an error is shown in the `MatSnackBar`. The `MatSnackBar` should be closed in the `ngOnDestroy` event of `SendFormComponent`, because currently the error message is not closed if the user navigates to another page.

**Comment by alexandermushinskiy** [comment]
The bug is fixed.
