### ISSUE TITLE
Problems obtaining node status

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#237]
This function is called to obtain the status of the node:
https://github.com/skycoin/skycoin-web/blob/0c93c5c11de35e845fe203b863364b94256671d8/src/app/services/blockchain.service.ts#L65-L76
Currently, if there is a connection error, what that function does is to stop the entire process of consulting the state of the node and 100% is shown on the screen. However, what the funtion should do is to try again after 90 seconds, because the current behavior makes the wallet completely unusable in case of connection error.

**Comment by Senyoret1** [comment]
Another option, possibly better, would be to show the user an error message, telling him to restart the browser. The header already has an error of that type, it would only be necessary to reuse the variable that activates it.

**Comment by alexandermushinskiy** [comment]
The bug is fixed.
