### ISSUE TITLE
Additional unit tests

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#253]
- In `cipher.provider.spec.ts` should be tested that when creating a transaction with an invalid destination address an error must be thrown.

- The tests in `cipher.provider.spec.ts` should be done again, but calling the functions from `WalletService`. Probably the best thing is to create a new unit tests file for `WalletService`, in which a real instance of `CipherProvider` is also used, not a simulated one.

- `WalletService` should test the `delete` function.

**Comment by alexandermushinskiy** [comment]
@Senyoret1, can we close this issue due to the PL was merged?

**Comment by Senyoret1** [comment]
Yes, this should have been closed automatically.
