### ISSUE TITLE
Ability to toggle between showing all and user's pending txs

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#275]
The pending transactions page should allow to choose between displaying only the transactions related to any of the user's wallets (just as it does now) or all pending transactions.

The functionality was added to the desktop wallet in https://github.com/skycoin/skycoin/pull/1627. However, the desktop wallet consults the pending transactions affecting the wallet with an api endpoint that can not be used in the web wallet, so the consultation process should be different (probably simpler).

To be able to switch between modes, the desktop wallet shows a double button in the navigation bar. To do so, modified versions of `DoubleButtonComponent` and `NavBarComponent` are used, as well as a new service: `NavBarService`. The modification of these components and the creation of the new service was done in https://github.com/skycoin/skycoin/pull/1590.

**Comment by gz-c** [comment]
"All" is not not necessary in the web wallet.  You can link to https://explorer.skycoin.net/app/unconfirmedtransactions

**Comment by AndreiIarovoi** [comment]
Could you, please, clarify the logic to retrieve all pending transactions and wallets related transactions?
As far as I understand "pendingTxs" API is used for all pending transactions. What is the logic for the wallets related transactions?

**Comment by Senyoret1** [comment]
Taking into account the last comment from gz-c, it will just be nedded to filter the pending transactions to show only the ones affecting any of the wallets of the user and add a link to https://explorer.skycoin.net/app/unconfirmedtransactions .

Yes, `pendingTxs` returns all pending transactions. What should be done would be to simply filter the transactions in `PendingTransactionsComponent.mapTransactions`.

**Comment by AndreiIarovoi** [comment]
So the first step is to get all pending transactions using the "/api/v1/pendingTxs" api. Then, use the "/api/v1/uxout?uxid='transaction_input'" api for each pending transactions inputs to figure out the wallets' addresses to filter results by user wallet. Is that correct logic?

**Comment by Senyoret1** [comment]
That approach sounds good. The V2 API will let to do it in a more optimal way, but it is still in development.

Also, filtering in `PendingTransactionsComponent.mapTransactions` was a quick sugestion, if you think that for some reason it would be better to do the filtering elsewhere, go ahead.
