### ISSUE TITLE
Wallet label is splitted up on two rows if length is too long

### ISSUE THREAD

**Issue by alexandermushinskiy** [skycoin/skycoin-web#282]
At the pic below the wallet label is `skycoin-web-e2e-test-load-wallet-seed`
![image](https://user-images.githubusercontent.com/30319973/41290176-ae1a4af4-6e54-11e8-8bc3-7ff5ea6c4d9e.png)

@Senyoret1, should we fix it somehow?
One of possible solution is to show ellipsis at the end and show tooltip with a full string.

**Comment by Senyoret1** [comment]
Yes, it should be fixed. What you propose sounds good.

**Comment by alexandermushinskiy** [comment]
The bug is fixed.
