### ISSUE TITLE
First steps to make the wallet compatible with Fiber coins

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#295]
Now that the wallet is relatively stable while working with Skycoin, it is posible to start making the necessary changes to make it work with the Fiber coins.

As an initial step, it is necessary to create a `coins` folder inside `src/app`. That folder must have a file with a base object containing the properties that the different coins of the wallet should have. For now, I think the properties should be:

- id (number): to be able to identify the coin in the code.
- nodeURL (string): URL of the node to which the wallet must connect to perform operations related to the coin.
- nodeVersion (string): version of the node software running in nodeURL.
- coinName (string): full name of the coin.
- coinSymbol (string): short name of the coin.
- hoursName (string): name of the coin hours produced by the coin.

The directory must also have a file for each compatible coin, containing an object that inherits from the previous object. For now, only one must be created, for Skycoin.

After adding those files, every wallet in `WalletsService` should haver a property indicating the id of the coin to which it belongs. Logically, currently saved wallets do not have that data, so it will be necessary to assign them a default value.

**Comment by alexandermushinskiy** [comment]
The issue is implemented and ready for the review.
