### ISSUE TITLE
Apply the redesign done in the desktop wallet

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#296]
Some important design changes were made in https://github.com/skycoin/skycoin/pull/1644. The same changes must be made in the web wallet, in the screens that are present in both wallets.

However, this change could significantly affect https://github.com/skycoin/skycoin-web/issues/271. @alexandermushinskiy, are you already working on that issue? It must be decided which one to solve first.

**Comment by alexandermushinskiy** [comment]
First we will implement UI changes.
