### ISSUE TITLE
Create transactions with the web worker

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#304]
Create the transactions in `CipherProvider.prepareTransaction` using the web worker. The code should be something like:

```
CipherWebWorkerHelper.ExcecuteWorker(CipherWebWorkerOperations.PrepareTransaction, {inputs: JSON.stringify(inputs), outputs: JSON.stringify(outputs)})
```

Also, with this change `CipherProvider` will no longer use `Cipher` directly, so `declare var Cipher;` should be deleted.

After making the change, verify if the UI correctly shows the spinner while the transaction is being created.

**Comment by alexandermushinskiy** [comment]
The issue is implemented.
