### ISSUE TITLE
Block navigation while creating a wallet in the wizard

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#305]
While creating a wallet in the wizard, the `DoubleButtonComponent` with the "New" and "Load" buttons must be disabled, to prevent the user from navigating. While disabled, the `DoubleButtonComponent` should be transparent. If there is an error, the `DoubleButtonComponent` must be enabled again.

Also, while creating a wallet, the "skip" button, besides being disabled, should be invisible.

**Comment by alexandermushinskiy** [comment]
The issue is implemented.
