### ISSUE TITLE
Apply the redesign in the pending transactions and outputs pages

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#306]
In https://github.com/skycoin/skycoin-web/pull/302 the redesign made in https://github.com/skycoin/skycoin/pull/1644 began to be applied. The redesign of the wallet page was done in that PR, but it is still necessary to change the design of the pending transactions and outputs pages.

The design has not yet been compiled in the Skycoin repository, so it is necessary to recompile the frontend of that repository in order to see it and use it as a reference.

**Comment by alexandermushinskiy** [comment]
The issue is implemented.
