### ISSUE TITLE
Create CoinService

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#308]
It is necessary to create a service for controlling the coins that are compatible with the wallet. In general, the service should have the following:

- An array in which all compatible coins can be consulted. The array must be filled with the objects contained in the files of the `src/app/coins` folder.
- A property with the currently selected coin. The currently selected coin must be a `BaseCoin` object. The property should be a `BehaviorSubject`, to be able to know when the coin has ben changed.
- A function for changing the current coin. The selected coin must be saved in permanent storage when calling the function, in order to be selected again when opening the wallet again.

**Comment by alexandermushinskiy** [comment]
The issue is implemented.
