### ISSUE TITLE
Improvements and fixes for the files with the data of the coins

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#309]
`src/app/coins/sky-coin.ts` should be renamed to `src/app/coins/skycoin.coin.ts` and the values of the following properties must be changed:

- `coinName`: Skycoin
- `hoursName`: Coin Hours

Additionally, the values of the `nodeUrl` and `nodeVersion` properties should depend on whether the wallet is running in development mode or in production mode (depending on the environment being used). At this time `nodeUrl` should be `/api/v1/` in development and `https://node.skycoin.net/api/v1/` in production (the values in the environment files), while `nodeVersion` should be `0.23.1-rc2` in development and `0.23.0` in production (the version of the develop branch of the node and the latest stable version).

Also, a file for a fake coin must be created in `src/app/coins`, for testing during development. The file would have the same structure as `src/app/coins/skycoin.coin.ts`. The name of the coin may be "Testcoin" or something similar, the important thing is that the data should be different from the data on the Skycoin file, except for the `nodeUrl` and `nodeVersion` properties. By keeping the same values of these properties, in the future the file will allow to show an additional coin in the UI, but that in reality is just an alias for Skycoin.

**Comment by alexandermushinskiy** [comment]
The issue is implemented.
