### ISSUE TITLE
Improvements for BlockchainService

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#311]
`BlockchainService.loadBlockchainBlocks` was created to run only once, when starting the wallet. However, when adding support for new coins, that function will have to be called each time the active coin is changed. This means that, for example, checking if the `IntervalObservable` is running and, if so, stop it.

Additionally, changing coins will bring complications, so it would be good to make changes to `BlockchainService.loadBlockchainBlocks` to avoid having a messy code for checking the node status. In general terms, `BlockchainService.loadBlockchainBlocks` should first check if the node is accessible and only then check periodically if the node is synchronized (this verification is currently done with `AppService.checkConnectionState`). With this change it will be possible to delete `AppService` and it will be more comfortable to handle the connection errors, which currently are send by both `AppService` and `BlockchainService`. When making this change, it would also be good to return better events in `BlockchainService.progressSubject`, since returning `999999999999` when the node is synchronized is not the best option. After making these changes, it will also be necessary to modify the wallet header, because it will surely stop working.

Also, it would be good to remove `BlockchainService.blocks`, since it is not used anywhere in the wallet, except in `BlockchainService.lastBlock`.

**Comment by alexandermushinskiy** [comment]
The issue is implemented.
