### ISSUE TITLE
Indicate the status of the secondary pages

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#314]
Currently, when there are no transactions, the History page simply shows the gray background and a slightly darker line. It would be more convenient to show a component with a message for the user like this:

![msg](https://user-images.githubusercontent.com/34079003/41482984-55b3196a-70a5-11e8-9485-89fb0f02a01f.png)
Additionally, the same component could be used while the information is being loaded, it would only be necessary to replace the text and the icon (with the spinner). In this way the user would have more information about what the wallet is doing, which would improve the UX.

The idea would be to use the component not only on the History page, but also on the Blockchain, Outputs and Pending Transactions pages. To be able to add it correctly in the Blockchain page, it would be necessary to wait for `blockchainService.lastBlock` and `blockchainService.coinSupply` to finish, before displaying the information on the screen.

The icon used in the image is https://material.io/tools/icons/?icon=announcement&style=baseline, its color is `#eaeaea` and have a size of about 50x50 px. The The color of the text is `#a9aaac`. The content has a margin of 50px with respect to the navigation bar (a similar margin should be used at the bottom).

**Comment by alexandermushinskiy** [comment]
The issue is implemented.
