### ISSUE TITLE
Remove main.js from .angular-cli.json

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#316]
Since `main.js` is used only in `cipher-web-worker.js` and `cipher-web-worker.js` is responsible for loading that file manually, `main.js` should be removed from
https://github.com/skycoin/skycoin-web/blob/1f1beb9e1cfdb83d5aa9059edd51602436bac995/.angular-cli.json#L26-L30
That change causes the wallet to start in half the time, in local tests.

**Comment by Senyoret1** [comment]
If the tests work, I guess there's no problem. The performance gain is more important.

**Comment by alexandermushinskiy** [comment]
The issue is implemented.
