### ISSUE TITLE
Hide wallets and addresses without outputs, in the outputs page

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#329]
Currently the outputs screen shows all the wallets and addresses. If an address has no outputs, the "No unspent outputs" message is displayed. This page should work like in the desktop wallet, where all the wallets and addresses without outputs are hidden. In case the page is opened and the user does not have any output, `LoadingContentComponent` must be shown with the "No unspent outputs" message.

However, as in the desktop wallet, if the page is open to see the outputs of a specific address, the address and its wallet must be displayed, regardless of whether it has outputs or not.

**Comment by alexandermushinskiy** [comment]
The issue is implemented.
