### ISSUE TITLE
Problems in the pending transactions page

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#331]
The pending transactions page have some errors:

- `LoadingContentComponent` is shown above the transaction list. For example, suppose that the pending transaction page is opened and there are no transactions for the current user, then the "All" button is pressed and a list of pending transactions that are not related to the user's wallets appears, if the user presses the "Mine" button, the loading animation will appear above the list and only after the load is finished the list is hidden to show again the message indicating that there are no pending transactions related to the user's wallets. While loading animation is displayed, the list of pending transactions should not be displayed.

- When navigating between screens, an incorrect list may appear. For example, suppose that the pending transactions page is opened and there are no transactions for the current user, then the "All" button is pressed and a list of pending transactions that are not related to the user's wallets appears,  if the user navigates to another page (like the wallets page, for example) and then returns to the pending transactions page, the "Mine" button will be selected, but the page will show the las list of transactions unrelated to the user's wallets. The list that is displayed does not correspond to the selected button.

**Comment by alexandermushinskiy** [comment]
The bug is fixed.
