### ISSUE TITLE
Fix the margins of ButtonComponent

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#332]
In https://github.com/skycoin/skycoin/pull/1657 the margin of the buttons was changed from `margin: 20px 10px;` to `margin: 20px 10px 0;`, eliminating the problematic lower margin. The same should be done in this repository.

Please keep in mind that after making that change, some `app-button ::ng-deep button` styles were deleted, because they were no longer needed. The same should be done in this repository.

**Comment by alexandermushinskiy** [comment]
The issue is implemented.
