### ISSUE TITLE
Get the names of the coins from CoinService

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#334]
Several pages show texts such as "SKY" and "Coin Hours", obtained through ngx-translate. These texts must be obtained from `CoinService.currentCoin`, in order to adapt the UI when changing the current coin. Some places where these texts are found are:

- The general header of the wallet.
- The top of the wallets page.
- The send coins form.
- The control with the preview of the transactions.
- The transaction history.
- The top of every wallet in the outputs page.
- The top of the pending transactions page.

Two less obvious places where the names of the coin are used are: the right side of the blockchain page and text at the top of the wizard.

After replacing the source of the texts, `common.coin-id`, `common.coin-hours` and `common.hours` should be deleted from `assets/i18n/en.json`.

**Comment by alexandermushinskiy** [comment]
The issue is implemented.
