### ISSUE TITLE
Get the CMC ticker ID from CoinService

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#335]
Currently `PriceService` always gets the dollar value using the ID stored in `PriceService.CMC_TICKER_ID`. For the wallet to be compatible with multiple coins, the ID must be obtained from `CoinService`. To do this it will be necessary to add an additional property to `BaseCoin`.

While doing this, please change the TestCoin id to -1, to avoid possible conflicts in the future.

**Comment by alexandermushinskiy** [comment]
The issue is implemented.
