### ISSUE TITLE
Allow to select the coin while creating a wallet

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#342]
For now the coin could be selected from a simple `<option>` in the modal screen for creating a wallet and in the wizard. The user must be able to select any of the coins in `CoinService.coins`.

**Comment by alexandermushinskiy** [comment]
@Senyoret1, as far as you know the same method `this.walletService.create()` is called when user either create or load a wallet. How should we handle selecting a coin when user is going to load a wallet?

**Comment by Senyoret1** [comment]
There is no way to identify the coin from the seed, so the user will have to select the coin using the `<option>`, as when creating a new wallet.

**Comment by alexandermushinskiy** [comment]
The issue is implemented.
