### ISSUE TITLE
Allow to change the current coin

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#343]
For now, a black bar with a simple `<option>` with all the available coins could be added at the top of the screen. After changing the coin in that `<option>`. When changing the current coin, only the wallets of that currency must be displayed, the balance must be updated, etc.

**Comment by alexandermushinskiy** [comment]
@Senyoret1, it's not clear where the <option> should be located. Could you please take a look at pic above (black rectangle), is that correct position?

![image](https://user-images.githubusercontent.com/30319973/41684919-98f835ca-74e7-11e8-839f-4e1046338679.png)

**Comment by Senyoret1** [comment]
Option 1 is ok, it is the least problematic to implement. After making wallet is fully compatible with multiple coins and solving the bugs that may appear, the graphic design will be polished.

**Comment by alexandermushinskiy** [comment]
@Senyoret1, we have some questions to clarify the correct behaviour.

Case A: when user changes the current coin and user does not have any wallet with new selected coin he will be redirected to the wizard, where user has ability to select any available coin. Is that OK?

Case B: if user selects a coin (without wallets) occasionally and he won't have ability to change coin back. What the behaviour should be?

Case C: user has selected Skycoin coin and have a wallet. He goes manually to the wizard and is going to create a wallet for the other coin (e.g. testcoin). Should we change current coin to the new one after a wallet has been created?

**Comment by Senyoret1** [comment]
Case A: Do not redirect the user to the wizard because it is not possible to change the coin from there, so the user may get stuck in case of changing the coin by accident. For now, if there are no wallets for the currency, just let the wallet screen go blank, we could add a warning message or something like that when polishing the UI / UX, but not at this moment.

Case B: I did not fully understand, but I think the answer to case A includes this. 

Case C: In theory, yes, the current coin should be changed. This will bring several unexpected errors, especially if the user has several tabs open, but at the moment they are not important. I have already thought about some solutions, but I would like to be able to review the changes made for solving this issue before deciding which approach to use. In fact, the solution for this issue will surely be quite long, so it would be mormal to have various new issues after implementing it.
