### ISSUE TITLE
Move all mock classes into one place

### ISSUE THREAD

**Issue by alexandermushinskiy** [skycoin/skycoin-web#346]
As far as you know we created mock classes for component unit-tests (to be able to mock services and pipes). Each test file has own list of mocks and as a result there are many mock classes which are the same. As an example you can search for `MockTranslatePipe`.

To avoid code duplication we propose to move all mocks to the one place (e.g. `app/utils/test-mocks.ts`) and use it in unit-tests. @Senyoret1, what do you think?

**Comment by Senyoret1** [comment]
Sounds good 👍

**Comment by alexandermushinskiy** [comment]
The issue is implemented.
