### ISSUE TITLE
Bug if more than one wallet has the same seed

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#354]
It is possible to create several wallets with the same seed, as long as they are for different coins, which is fine. However, `WalletService` has several places in which to find a wallet inside `WalletService.wallets` the code just checks if the first address match, which was good before, but not any more, because more than one wallet could have the same first address. One place where that happens is:
https://github.com/skycoin/skycoin-web/blob/0c032d58577f59e92f76cefcc346b8ab51b502ba/src/app/services/wallet.service.ts#L175-L189
Because of the use of this method for finding the wallet, if you create a wallet for Skycoin and then another one for Testcoin, with the same seed, when you try to unlock the Testcoin wallet, the code unlocks the Skycoin one. But that is no all, the Skycoin wallet disappears in the UI and two wallets appear in the Testcoin list, instead of one, which is a pretty erratic behavior.

To solve this, a more accurate search method must be used. Another place in which this method is used, is:
https://github.com/skycoin/skycoin-web/blob/0c032d58577f59e92f76cefcc346b8ab51b502ba/src/app/services/wallet.service.ts#L148-L156

**Comment by AndreiIarovoi** [comment]
There should not be any issues with the lines 148-156 of "wallet.service" since the wallet is passed into "createTransaction" method and we consider that different API will be used for different coins in order get outputs based on the wallet's addresses. Could you, please, clarify that it is right approach?

**Comment by Senyoret1** [comment]
Yes, you are right, there is not problem in that part.
