### ISSUE TITLE
Design for choosing coins

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#369]
Note: this design should NOT be implemented immediately, I put it here to get opinions.

Currently the wallet allows to select different coins, but the design is very simple. To change the coin, simply use the `<select>` in the upper right corner:
![ac1](https://user-images.githubusercontent.com/34079003/41883719-fa4eea10-78bd-11e8-9d82-0db8f91c9f8c.png)
I did some tests (in an image editor, there is still no written code) and I think the appearance would improve using this style (expand the image to see the details):
![ds1](https://user-images.githubusercontent.com/34079003/41883731-0878cad4-78be-11e8-96a3-2a41a971a235.png)
It is a relatively simple change, which does not break the current graphic style. Previously I was testing another design, I do not like it that much (because it is less consistent with the current design and would be more difficult to integrate it with the desktop wallet later, if required), but I put it here just in case:
![ds2](https://user-images.githubusercontent.com/34079003/41883770-2f23e2fe-78be-11e8-989d-23805a77517a.png)
Additionally, I think it would be good to show the coin list in a modal window, like this one:
![ds3](https://user-images.githubusercontent.com/34079003/41883777-376674c2-78be-11e8-8fe9-f069c3bb24b1.png)
Any opinion is welcome.

Ping: @gz-c

**Comment by alexandermushinskiy** [comment]
The modal window with a list of available coins it's really nice feature and more informative. 
It's include additional info: already created wallets, the amount of coins and hours.
In that case the link-button could be used instead of select-options (it will not take many spaces as it does select-options).

**Comment by Senyoret1** [comment]
@alexandermushinskiy, that would be an option. The appearance would be almost the same, just without the arrow. However, I think that keeping the arrow would be more appropriate, because it indicates to the user that when pressing there he will be able to choose between several options. A simple button gives less information and some users are afraid to press the buttons just to see what they do, because they could "break" something.

@mahansky, with ghost buttons it would look like this:
![ds4](https://user-images.githubusercontent.com/34079003/41946273-8deeea24-797f-11e8-9a53-513e9b8f44cb.png)
I think it looks good. The thing that worries me is how the icons will look on that background. The white background ensures that almost any icon looks good without many changes. Additionally, in the future the background will probably change according to the selected coin.

**Comment by Senyoret1** [comment]
With the circular side edges it looks like this (I put the images with the full browser window because sometimes the buttons look good when they are alone but not very so much when they are next to the other elements):
![ds5](https://user-images.githubusercontent.com/34079003/41947777-97b1e2fc-7987-11e8-8065-311ec130ca9e.png)
![ds6](https://user-images.githubusercontent.com/34079003/41947783-9c7cb6d6-7987-11e8-8fc4-b43d7ba841c4.png)
The two designs are consistent with the other elements of the wallet. Maybe the rectangular ones are a little more consistent, but I think they look a little better with the completely rounded edges.

**Comment by gz-c** [comment]
I don't know if the modal window will scale when there are 10s of coins a user may have

**Comment by Senyoret1** [comment]
@gz-c, with smaller icons and scrolling there should be no problem to add a large number of coins, we could even add a search field at the top. However, thinking about what you said, another option could be to use something relativelly similar to the Mac OS Launchpad:

![launchpad](https://user-images.githubusercontent.com/34079003/42007350-97d54e38-7a4d-11e8-8356-159380e59930.png)

![ds7](https://user-images.githubusercontent.com/34079003/42009013-7c65e12c-7a56-11e8-94dc-08b5eec18ff7.png)

I created the design with few icons because in the Launchpad is posible to see that it should look good with many icons, it only remained to see if it looked good with few. I used only the icon, instead of the icon with the name, as in the design of the modal window, because surely the designs of the different coins are going to be very inconsistent and some are not going to fit well (like the Solar Bankers logo, which it is not very rectangular), but almost all coins have an icon that fits well in a square. I also removed the balance because it could cause problems if the user has wallets for many coins.

There is a small disadvantage with this design: the background is not totally white, so the icons should have a transparent background. However, almost all coins should have an icon with transparent background and we could try to fix manually the few problematic ones.

**Comment by Senyoret1** [comment]
@mahansky I think we can start doing this, using these designs:
![ds6](https://user-images.githubusercontent.com/34079003/41947783-9c7cb6d6-7987-11e8-8fc4-b43d7ba841c4.png)
![ds7](https://user-images.githubusercontent.com/34079003/42009013-7c65e12c-7a56-11e8-94dc-08b5eec18ff7.png)
