### ISSUE TITLE
Refresh faster if the node is almost synchronized

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#376]
Currently, when starting the wallet the code verifies if the node is synchronized and, if it is not, the verification is done again after 90 seconds. However, it is not too uncommon to see that the node needs only one block to be completely synchronized, case in which 90 seconds is too much. These cases usually happen when a transaction has recently been made and is still not fully replicated, so the node is not re-downloading the blockchain due to a problem.

If the node only needs 5 blocks or less, the verification should be done again after 5 seconds, instead of 90.

**Comment by alexandermushinskiy** [comment]
The issue is implemented.
