### ISSUE TITLE
Connect to the URL that corresponds to the coin

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#386]
Server connections must be made using the URL of the currently selected coin, in `CoinService.currentCoin.nodeUrl`.

**Comment by alexandermushinskiy** [comment]
Could you please clarify this issue in more details?

**Comment by Senyoret1** [comment]
Currently, when making http connections to the server (node), the first part of the URL is obtained from `environment.ts` - `environment.prod.ts` and `proxy.config.js`.

That method includes a single URL, that of the Skycoin node, but each coin use a different node, in a different URL. That is why `BaseCoin` has a `nodeUrl` property, to be able to know which is the URL of the node of each coin.

What should be done from now on is to obtain the data from the URL stored in the `nodeUrl` property of the current coin, instead of using the data from `environment.ts` - `environment.prod.ts`.

**Comment by alexandermushinskiy** [comment]
Thank you for the clarification, the issue is implemented.
