### ISSUE TITLE
Delete DateFromNowPipe

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#389]
In theory, `DateFromNowPipe` shows how much time has passed since a date. However, because the date returned by the server is compared with the local date, it is not strange to see that a past event will happen in the future, even more so if the user's date is not properly configured. Because of the way in which dates are added to the blockchain, it is unlikely to be able to obtain a base date from the server to make `DateFromNowPipe` more accurate. Because of this, it is better to remove the pipe and simply show the full date in the places where it is being used.

**Comment by alexandermushinskiy** [comment]
The issue is implemented.
