### ISSUE TITLE
Improve the initialization of LanguageService

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#390]
Currently, the `LanguageService.currentLanguage` subscription in `HeaderComponent` is receiving two quick events when opening the wallet, being that it should receive only one, with the default language or the one stored in `localStorage`. This is probably because `LanguageService.currentLanguage` is initialized with the default language.

Part of the solution for this may be to remove `LanguageService.loadLanguageSettings` and place all the initialization code in the constructor (which would also help make the code cleaner).

**Comment by alexandermushinskiy** [comment]
The issue is implemented.
`LanguageService.loadLanguageSettings` was not removed due to onboarding components will not be translated (if there is no wallets). In that case the language settings (list of languages, current language) were not be loaded, that is why we added it in `app.component`.
