### ISSUE TITLE
We have to give the seed to see the addresses we just created

### ISSUE THREAD

**Issue by iketheadore** [skycoin/skycoin-web#551]
After creating a wallet with a seed, we have to input the seed again to "unlock" the wallet to see the addresses, actually the wallet is not locked as the sensitive data are all exist in the memory. The seed should only be required when necessary, like when sending coins or adding new addresses.

**Comment by Senyoret1** [comment]
The reason for that behavior is this:

We asked some end users to test the wallet, they saw that the wallet is very similar to the desktop wallet and got the idea that it would save the seed, just as the desktop wallet does. The end result was that a good number of them did not save the seed, send very small amouts to the newly generated addresses and the funds were lost after refeshing the browser.

To avoid that, when creating a new wallet (not when using the option to load an existing wallet) the user must enter the seed again to be able to see the address, as a way to ensure the user has saved the seed before being able to see the address and send any funds to it. At some point I even added the requeriment of adding an extra character at the end of the seed, to force the user to read the warning before being able to confim the seed, but that change was reverted to avoid confusing the user (some people could think that the extra charater is part of the seed).

Taking this into account, the second wallet confimation can be removed, but another method for ensuring the user has saved the wallet would have to be used. Maybe a red bar at the top (like the current yellow one that warns that the app is in beta state) warning the user all the time?

**Comment by Senyoret1** [comment]
@mahansky

**Comment by mahansky** [comment]
I don't have any strong opinion about this, I like the current solution. I would expect it to skip this verification when I **load** a wallet (not sure if that's the case rn)

**Comment by gz-c** [comment]
I agree with that mahansky says about loading (it should skip)

**Comment by Senyoret1** [comment]
That is how it is working right now: the verification only appears when using the option for creating a new wallet and is omitted when using the option for loading an existing wallet, both when using the wizard and the options of the wallets list (I just checked it just in case).

As it has the desired behavior, I'm closing this issue, but fell free to reopen it if you think it should not be closed yet.
