### ISSUE TITLE
Add big disclaimer warning, persistent on every page

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin-web#59]
Add a persistent warning banner that says "IF YOU USE THIS WALLET YOU MAY LOSE COINS. TESTING PURPOSES ONLY."

Use a feature flag to enable/disable this.

**Comment by alexandermushinskiy** [comment]
@gz-c, the issue is implemented and merged, so it can be closed.

**Comment by gz-c** [comment]
@alexandermushinskiy can you link the issue?

**Comment by alexandermushinskiy** [comment]
@gz-c, I meant the current issue - "Add big disclaimer warning, persistent on every page"

**Comment by AndreiIarovoi** [comment]
https://github.com/skycoin/skycoin-web/pull/80
