### ISSUE TITLE
Address malformed when sent

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin-web#60]
User reports they tried to send a transaction to UY2doJMGfMg1f2aBx4ugkQwPigJM7SgV1o and the client sent it to 111111111111111111111691FSP instead.

The related transaction is https://explorer.skycoin.net/app/transaction/172709f2ead189f58d00c0b4a83c4b3afdf5a57c6d8199c52f83caaaaffe87e0

**Comment by therealssj** [comment]
`111111111111111111111691FSP` means the address was empty
when you do `string(base58.Hex2Base58(addr.Bytes()))` on an empty address var what you get is `111111111111111111111691FSP`

**Comment by gz-c** [comment]
OK, definitely easier to find in the client then.

Wondering if we should look for empty addresses in all client APIs and reject if it contains one.  Don't know if we should go as far as rejecting transactions which contain an empty address, but it's probably reasonable to enforce it at the API layer (in this case, `/injectTransaction`)

**Comment by Senyoret1** [comment]
The error could be due to this: https://github.com/skycoin/skycoin-web/issues/72 . However, I'm not entirely sure, so I created another issue.

**Comment by Senyoret1** [comment]
The error is that, when an invalid address is entered, skycoin-lite changes the address to 111111111111111111111691FSP, instead of failing. At this time the wallet does not clean the text entered by the user, so a simple white space at the end is enough for the problem to happen. Will look for a solution for this.

**Comment by alexandermushinskiy** [comment]
@Senyoret1, is this issue still actual?

> At this time the wallet does not clean the text entered by the user, so a simple white space at the end is enough for the problem to happen.

It was fixed in the issue #121.

**Comment by Senyoret1** [comment]
@alexandermushinskiy, it should have been solved in https://github.com/skycoin/skycoin-web/pull/84, https://github.com/skycoin/skycoin-web/issues/121 and https://github.com/skycoin/skycoin-web/pull/203. If there is still a problem, it should be detected when solving https://github.com/skycoin/skycoin-web/issues/241
