### ISSUE TITLE
Problems in the process for creating transactions

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#69]
The way in which `WalletService.sendSkycoin` work creates excessively large transactions and a greater spending of coin hours than necessary. For each transaction, all the outputs are being used, instead of making a calculation about the outputs that are necessary. Additionally, the calculation causes hours with decimals to be sent, which is not allowed. As a reference, the node function that creates the transactions for the desktop wallet is `src/wallet/wallet.go/CreateAndSignTransactionAdvanced` (https://github.com/skycoin/skycoin/blob/develop/src/wallet/wallet.go#L1026).

**Comment by Senyoret1** [comment]
This probably should wait for https://github.com/skycoin/skycoin/issues/1419

**Comment by gz-c** [comment]
this doesn't depend on that issue
