### ISSUE TITLE
Outputs order

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#71]
In the desktop wallet, the first output of the transactions is the one used to return the remaining coins and hours. Currently the web wallet is reversing the order, the output for the returning the remaining coins and hours is placed at the end.

**Comment by gz-c** [comment]
`POST /wallet/transaction` adds the change address at the end

**Comment by Senyoret1** [comment]
My bad. Previously the desktop wallet added the return address first, I didn't notice that `/wallet/transaction` reversed the order. There is no problem then.
