### ISSUE TITLE
Transactions are created without inputs, outputs and signatures

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#72]
There is a problem with the transaction creation procedure, which is used in the send coins page. Because of this, the transactions that are sent to the node do not have inputs, outputs or signatures, which makes them invalid.

The problem is somewhat complicated, it is in the client code, but not in any of the .ts files, but in a .go file from another repo that is converted into to .js. Apparently in order to avoid compatibility problems, the web wallet includes the `src/assets/main.js` file, which is a `.js` created using gopherjs. The Go code that is used to create that file is in a repository called skycoin-lite (https://github.com/samuelvisscher/skycoin-lite). Here are the results of some tests that could be used as a starting point to fix the problem:

When a transaction is going to be created in `WalletService.sendSkycoin` (https://github.com/skycoin/skycoin-web/blob/master/src/app/services/wallet.service.ts#L57), an array with the inputs is created, as well as another with the outputs. Next, those arrays are sent to `this.cipherProvider.prepareTransaction`, which is a function written in Go (https://github.com/samuelvisscher/skycoin-lite/blob/gopherjs/liteclient/client.go#L44), to get an encoded transaction.

To test how the function works, so, as an example, we could send the following arrays as parameters to `this.cipherProvider.prepareTransaction`, inside `WalletService.sendSkycoin`:
`[{"hash":"894db6abdef5fa502ac6c50cd39a681f4e5ca1ceb099e735fd3d5194696a41d7","secret":"123"}]`

`[{"address":"2eStQdZ9a4HSmGtWwgVvz3av76P4kw5se5c","coins":1000000,"hours":5},{"address":"2EPwCG2peoy7L6E8ZFCYQLy7zeNGUngopTK","coins":47000000,"hours":5}]`

The result returned by this.cipherProvider.prepareTransaction is this:
`3100000000af5570f5a1810b7af78caf4bc70a660f0df51e42baf91d4de5b2328de0e83dfc000000000000000000000000`

The result can be deserialized by creating an .go file in a copy of the Skycoin node, with the following code:
```
package main
import (
	"fmt"
	"encoding/hex"
	"github.com/skycoin/skycoin/src/coin"
)
func main() {
	bytes,_ := hex.DecodeString("3100000000af5570f5a1810b7af78caf4bc70a660f0df51e42baf91d4de5b2328de0e83dfc000000000000000000000000")
	tx := coin.MustTransactionDeserialize(bytes)
	fmt.Printf("%+v\n", tx)
}
```

The result is this:
`{Length:49 Type:0 InnerHash:[175 85 112 245 161 129 11 122 247 140 175 75 199 10 102 15 13 245 30 66 186 249 29 77 229 178 50 141 224 232 61 252] Sigs:[] In:[] Out:[]}`

Evidently there is a serious error in the procedure: the three arrays at the end are empty and the calculated size is greater than zero. If more inputs are added to the transaction, the result is the same.

I’m not sure if this error is the one that causes the failure reported in https://github.com/skycoin/skycoin-web/issues/60, but it is clear that it is a serious error.

Additional tests are needed to determine whether the error is a problem with the Go code or a problem with the javascript version created by gopherjs. But there is also the question of whether it is better to review the Go code or simply migrate everything to Typescript, since having two code bases as now is quite inconvenient. Obviously, if everything is changed to typescript, an exhaustive review process should be carried out, which in my opinion should include even the parts that were already migrated to typescript, such as the creation of seeds (https://github.com/skycoin/skycoin-web/blob/master/src/app/components/pages/onboarding/onboarding-create-wallet/onboarding-create-wallet.component.ts#L110). However, this is also true for changes made in the Go code.

**Comment by gz-c** [comment]
I don't know if the cryptographic operations (address generation, code signing) can be reasonably ported to typescript by hand.

Other operations could be done with typescript.

**Comment by Senyoret1** [comment]
At first I thought that skycoin-cipher-web was the library used in this repository, but I took a quick look at the code and it seems that it does not include instructions to create transactions, so it may need some work in order to be usable.

There is also cordova-skycoin-liteclient (https://github.com/skycoin/skycoin-mobilewallet) which uses a compiled .aar file, surely created with the Go code; Java to access that compiled file and javascript to access the Java code. With all this, defining a single library would be very good for the maintainability of the different repos.

As for the repository created by Spaco, I did not know it. However, it seems that it is specifically designed for mobile apps, because it compiles .jar and .aar files. I did not see anything related to Typescript or Javascript.

Taking all this into account, the two viable options seem to be to work with skycoin-lite or create a Typescript code.

Regarding the latter, as you say, it is very impractical to port all the code to Typescript by hand. In fact, having only one type of numeric variable in Javascript is a major problem that makes the process very difficult. However, there are libraries with most of the heavy work already done. The two main libraries I know could be helpful are crypto-js (https://github.com/brix/crypto-js) and cryptocoinjs (https://github.com/cryptocoinjs/cryptocoin). The first one is a general purpose cryptography library. The latter was created specifically for crypto currencies, it is modular (it is actually a set of many separate repositories) and has almost everything necessary to create addresses, signatures, etc.

**Comment by gz-c** [comment]
The javascript crypto libraries may not actually behave 100% the same as ours, hence I would prefer to transpile.

skycoin-lite is the most complete one to continue with?

The spaco one may still be usable for this case, if it is more complete.  They developed for use in mobile, but if it can be transpiled to javascript as well, then it's fine.  I think the underlying go codebases can be mostly shared between web and mobile.

**Comment by Senyoret1** [comment]
I think it is. However, I can do some testing with the Spaco library, to see if it is more complete. One thing, I don't know if it's important, but I just saw that the Spaco library has a GPL license, I mention it just in case.

**Comment by Senyoret1** [comment]
After extensive testing, it turns out that the problem is quite simple: in https://github.com/skycoin/skycoin-web/blob/master/src/app/services/wallet.service.ts#L79 two json strings are sent to `this.cipherProvider.prepareTransaction`, but in https://github.com/skycoin/skycoin-web/blob/master/src/app/services/cipher.provider.ts#L18 those two string are again encoded as json, completely damaging the json format. That made Go to return null while doing `json.Unmarshal` in https://github.com/samuelvisscher/skycoin-lite/blob/gopherjs/liteclient/client.go#L48-L49. A simple error, but difficult to debug.

With all this in mind, the solution is to change https://github.com/skycoin/skycoin-web/blob/master/src/app/services/cipher.provider.ts#L18 to:
`return Cipher.PrepareTransaction(inputs, outputs);`

During the tests, I could not find the error reported in https://github.com/skycoin/skycoin-web/issues/60, so it may still be present.

On the other hand, skycoin-lite seems to be working correctly, so it may not be necessary to use another library. At this time, it only makes 2 functions available: one for creating an address from a seed (it includes the seed needed for the next address) and another for creating transactions. Those two functions seem sufficient for now.

**Comment by gz-c** [comment]
If we are proceeding with skycoin-lite, I would like to move it into our organization, and remove skycoin-cipher-web

**Comment by gz-c** [comment]
We will need a test case to make sure this bug does not reappear

**Comment by Senyoret1** [comment]
I agree. also tests should be added to skycoin-lite and in this repo, with the result of: https://github.com/skycoin/skycoin/issues/1436
