### ISSUE TITLE
The header style need some fixes

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#85]
The style of the header is different from that of the desktop wallet. The desktop wallet looks like this:
![original](https://user-images.githubusercontent.com/34079003/39715319-e49b48f6-51fa-11e8-8f7d-7be76b8ad111.png)
And the web wallet looks like this:
![wseb](https://user-images.githubusercontent.com/34079003/39715344-f1ac6296-51fa-11e8-9a37-2ea04fb714e4.png)
The two should look the same. The problems are: typography is thicker in the web wallet and the dollar amount is not centered.

Please use as a reference the code code found in https://github.com/skycoin/skycoin/tree/develop/src/gui/static/src/app/components/layout/header

**Comment by alexandermushinskiy** [comment]
Fixed and PR has been created
