### ISSUE TITLE
Problems when trying to unlock a wallet with an incorrect seed

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#87]
Steps to reproduce:

- Access the wallet screen.
- Press the lock icon of any locked wallet, to unlock it.
- In the modal window, write an incorrect seed and press "Unlock". An error should appear indicating that the seed is incorrect.
- Close the modal window by pressing "Cancel".

What happens when performing these steps is that the wallet screen shows the wallet as unlocked, being that the unlocking process should have failed. In fact, the wallet happens to have a wrong secret assigned in `WalletService.wallets`. This means that it is no longer possible to try to unlock the wallet (unless the browser is refreshed) and that when trying to send coins the transaction will be signed with the wrong secret stored in `WalletService.wallets`.

**Comment by alexandermushinskiy** [comment]
Fixed, PR has been created.
