### ISSUE TITLE
The balance of the addresses is calculated incorrectly

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#95]
The `WalletService.loadBalances()` function (https://github.com/skycoin/skycoin-web/blob/master/src/app/services/wallet.service.ts#L235), which is responsible for updating the balance, currently only considers the last output of each address. That means that if, for example, the user has an address with two outputs, one with a coin and other with 2, the balance indicated by the wallet will be just 2 coins, not 3, as it should.

**Comment by alexandermushinskiy** [comment]
Fixed, PR has been created.
