### ISSUE TITLE
The wallet is not periodically updated

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#96]
Due to this problem, if the user receives coins while the wallet is open, he will not be able to see the updated balance until the browser is manually refreshed. Like the desktop wallet, the balance of the web wallet could be updated every 30 seconds, but some users will leave the wallet open for a long period of time without use, which would cause unnecessary bandwidth usage.

An alternative would be to refresh only every 5 minutes and add a text indicating since how many minutes the information was updated. The text could look like this:
![time-updated](https://user-images.githubusercontent.com/34079003/39784960-5e8be86c-52e8-11e8-829a-9789c8663aa0.png)

Another alternative would be to refresh the balance every 30 seconds while the browser window is active and every 10 minutes while it is not. This option is a bit more complicated because the best method could have compatibility problems if the browser is not updated: https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API#Browser_compatibility . Or we could simply use the `window.onfocus` event, but it reports `true` when the window is active, regardless of whether the user is using another tab.

What do you think of this, @gz-c ?

**Comment by gz-c** [comment]
Could add a refresh button too

**Comment by Senyoret1** [comment]
So it seems good to you if option 1 is implemented? I think that, at least for now, it is the most convenient option, because it is simpler, which could avoid some unpleasant surprises in the near future..

**Comment by gz-c** [comment]
Nevermind, no need for a refresh button, unless reloading the page would reset their state

Every 5 minutes is fine.

Although, before sending we'd probably want to refresh the balance, to make sure the outputs we're using match the balance displayed.

**Comment by alexandermushinskiy** [comment]
The issue has been implemented, PR is created.
The flow is: 
- every 5 minutes wallets balances are updated (without refresh a page)
- the time (in a minutes) how long ago balances were updated is shown in a header;
- no refresh button.

**Comment by alexandermushinskiy** [comment]
@Senyoret1, please be informed that your review comments are fixed.
